baseURL = "https://jimzenn.com/"
languageCode = "en-us"
title = "Jim Zenn"
author = "Jim Zenn"
theme = "zealoft"
preserveTaxonomyNames = true
googleAnalytics = "UA-83942334-3"

[params]
  my_legal_name = "Qingwei Zeng"
  my_preferred_name = "Jim"
  my_education = "University of California, Los Angeles"
  phone = "+1 (510) 508-2766"
  tel = "+15105082766"
  email = "zenn@ucla.edu"
  expected_graduation = "March 2020"
  my_major = "Math of Computation"
  github = "https://github.com/Jim-Zenn"
  CV = "/Jim_Zenn-CV.pdf"
  version = "2.9.9.9.3"

# [menu]
#   [[menu.main]]
#     identifier = "math-115A"
#     name = "Math 115A"
#     url = "/math-115a/main/"
#     weight = 1

[taxonomies]
  category = "volumes"
  tag = "keywords"
